apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: 'softtekcoeapisms/adservice:1.0'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    name: adservice
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: adservice
  type: ClusterIP